# Generated by Django 5.1.2 on 2024-11-01 07:12

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='userToken',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user', models.CharField(blank=True, max_length=255, null=True)),
                ('authToken', models.CharField(blank=True, max_length=256, null=True)),
            ],
            options={
                'db_table': 'users_token',
            },
        ),
        migrations.AlterField(
            model_name='user',
            name='modified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
