# Generated by Django 5.1.2 on 2024-11-01 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_alter_event_modified_at_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='eventattendee',
            unique_together=set(),
        ),
    ]
