# Generated by Django 5.1.2 on 2024-11-01 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_alter_eventattendee_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='eventattendee',
            unique_together=set(),
        ),
    ]
